### ISSUE TITLE
🐛cloudflared.service: Main process exited, code=killed, status=4/ILL

### ISSUE THREAD

**Issue by 1cg1** [cloudflare/cloudflared#1154]
cloudflared version 2024.1.2

Running fine, and has been since the update, but today dns requests failing, looking into it whenever I try to start the cloudflared.service running on my raspberry pi (all software up to date) I run into the following error:

sudo systemctl status cloudflared
● cloudflared.service - cloudflared DNS over HTTPS proxy
     Loaded: loaded (/etc/systemd/system/cloudflared.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: signal) since Sun 2024-01-14 17:52:03 GMT; 7s ago
    Process: 860 ExecStart=/usr/local/bin/cloudflared proxy-dns $CLOUDFLARED_OPTS (code=killed, signal=ILL)
   Main PID: 860 (code=killed, signal=ILL)
        CPU: 20ms

looking into journalctl reveals the following:
Jan 14 17:47:57 DietPi systemd[1]: cloudflared.service: Main process exited, code=killed, status=4/ILL
Jan 14 17:47:57 DietPi systemd[1]: cloudflared.service: Failed with result 'signal'.
Jan 14 17:48:07 DietPi systemd[1]: cloudflared.service: Scheduled restart job, restart counter is at 36.
Jan 14 17:48:07 DietPi systemd[1]: Stopped cloudflared DNS over HTTPS proxy.
Jan 14 17:48:07 DietPi systemd[1]: Started cloudflared DNS over HTTPS proxy.

can't find a reference for status 4/ILL anywhere, apologies if I have just missed it. 
My /etc/default/cloudflared is the standard one:
##Commandline args for cloudflared, using Cloudflare DNS
CLOUDFLARED_OPTS=--port 5053 --upstream https://1.1.1.1/dns-query --upstream https://1.0.0.1/dns-query

Any help much appreciated. Any more info needed please let me know.

**Comment by kazulk** [comment]
I have the same issue as well. Only difference is I am running raspberry pi os bookworm.

**Comment by GitUserTx** [comment]
I have the same error on Raspbian 11 lite 32bit on Pi Zero W. All six install has same error. If I have the SD card to Pi Zero 2 W, it works just fine.

**Comment by 1cg1** [comment]
> I have the same error on Raspbian 11 lite 32bit on Pi Zero W. All six install has same error. If I move the SD card to Pi Zero 2 W, it works just fine. I have the same set up in three different household. It is setup to auto update. All six went down.

Wondering if it is maybe a hardware problem? I run it on a first gen RPi Model B. But then again, I have been running this for close to a year without issue, as well as the latest version since it came out with no issues. Will look into if using the previous version fixes for me and report back.

**Comment by reggie88** [comment]
Get the same on a RPi 1B, but runs fine on a RPi 3B+. The last version i'm able to get running on the 1B is 2023.10.0.
 
Also `cloudflared -v` gives me `Illegal instruction` instead of displaying the version on the 1B when trying any of the 2024 releases.

**Comment by 1cg1** [comment]
> Get the same on a RPi 1B, but runs fine on a RPi 3B+. The last version i'm able to get running on the 1B is 2023.10.0.
> 
> Also `cloudflared -v` gives me `Illegal instruction` instead of displaying the version on the 1B when trying any of the 2024 releases.

Guessing it's a hardware thing then, a shame as the first gen Pi has been running this with Pihole without issue for a year+. Will try the version you suggested after work.

**Comment by jcsf** [comment]
Hi,
Sorry, all for the inconvenience, we are aware and are already working on a fix, to generate the proper binaries for older versions of ARM, this commit e5ae80ab861aa0b48d5101790187fdf4da0c18d2, should fix the issue and the next release should be working properly.

**Comment by jcsf** [comment]
2023.1.3 is out, please test it in your older ARM version devices.

**Comment by Pythbit** [comment]
It is still failing for the same reason on a Raspberry Pi 1 B+, but at this point I should probably just upgrade!

**Comment by reggie88** [comment]
> [2023.1.3](https://github.com/cloudflare/cloudflared/releases/tag/2024.1.3) is out, please test it in your older ARM version devices.

It works on my Pi 1B, thanks!

**Comment by kazulk** [comment]
> [2023.1.3](https://github.com/cloudflare/cloudflared/releases/tag/2024.1.3) is out, please test it in your older ARM version devices.

Works on my Pi Zero W, thanks for fixing it so quick.

**Comment by 1cg1** [comment]
> > [2023.1.3](https://github.com/cloudflare/cloudflared/releases/tag/2024.1.3) is out, please test it in your older ARM version devices.
> 
> It works on my Pi 1B, thanks!

Did you just sudo apt update or install from the .deb file on github? Both still fail for me with illegal instruction.
What OS are you running as I'm running same hatrdware so would like to try your setup as you have it working!

**Comment by reggie88** [comment]
> Did you just sudo apt update or install from the .deb file on github? Both still fail for me with illegal instruction. What OS are you running as I'm running same hardware so would like to try your setup as you have it working!

I used this guide (https://docs.pi-hole.net/guides/dns/cloudflared/) a few years back to set it up, following the armhf architecture part and copied the manual update process into a .sh file that I run when there's an update. It uses the arm binary and runs it once everything is configured. I'm running Raspbian 10 (buster).

**Comment by 1cg1** [comment]
> > Did you just sudo apt update or install from the .deb file on github? Both still fail for me with illegal instruction. What OS are you running as I'm running same hardware so would like to try your setup as you have it working!
> 
> I used this guide (https://docs.pi-hole.net/guides/dns/cloudflared/) a few years back to set it up, following the armhf architecture part and copied the manual update process into a .sh file that I run when there's an update. It uses the arm binary and runs it once everything is configured. I'm running Raspbian 10 (buster).

Thanks for the instructions. 
In the end I waited for a new version as I like being to update straight from the repository.
Can confirm working again on old arm (RPi B) with udpdate 2024.1.5
