### ISSUE TITLE
'illegal instruction' on ARM platforms 🐛

### ISSUE THREAD

**Issue by JeremyLoy** [cloudflare/cloudflared#1167]
I just upgraded to 2024.1.5 via apt which contains 3ad4b732d45cdc400154f227c18781885fe49b71 but I'm still seeing `Illegal instruction`, even when just trying to run `cloudflared --version`.

I'm not trying to be a bother, but #1163, #1162, and #1136 are all closed 

I did find #583 from several years ago that does have a solution, albeit it lets you install `arm` instead of `armhf` via the package manager.

---

If I scp the `linux-arm` binary over to my Pi, that one indeed works correctly. 

~~I believe that 3ad4b732d45cdc400154f227c18781885fe49b71  needs to apply to `armhf` as well (not just `arm`). ~~

---
EDIT:

https://github.com/golang/go/issues/61588

Actually, looks like this relatively recent go issue might have the solve we're looking for.

The principal issue here is whether soft/hardware floating point exists, not necessarily the ARM version. Having to specify ARM=5 was a weird workaround but now it seems to be parameterized

**Comment by OakAtsume** [comment]
Hello, I wanted to confirm that I've also been experiencing this issue; using the latest deb/binary file(s).
where the binary seems to crash and the simply return the message `Illegal instruction`

**Comment by joliveirinha** [comment]
I believe this was fixed in the latest release. you should use the arm deb

**Comment by svde** [comment]
Issue is still there, even with the latest version. 

$ cloudflared --help
Illegal instruction

$ dpkg --print-architecture
armhf

$ dpkg -l cloudflared
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  cloudflared    2024.4.0     armhf        Cloudflare Tunnel daemon

A bit strange to suggest to use a different architecture.

**Comment by pew** [comment]
Not the best solution, but I managed to install cloudflared on my Raspberry Pi Zero by adding the arm architecture to the system and specifying arm as the architecture in my sources.list file:

```
dpkg --add-architecture arm
```

entry in sources.list

```
deb [arch=arm signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared buster main
```
