### ISSUE TITLE
2021.1.1 doesn't log to specified log file anymore

### ISSUE THREAD

**Issue by vidarak** [cloudflare/cloudflared#292]
config line:
logfile: c:\cloudflared\cloudflared.log

Even running a tunnel list throws errors regarding logs:
PS C:\cloudflared> .\cloudflared.exe tunnel list
{"level":"error","time":"2021-01-13T19:38:33Z","message":"Falling back to a default logger due to logger setup failure:
mkdir : The system cannot find the path specified."}

**Comment by nmldiegues** [comment]
Hello @vidarak .

I've just confirmed that running cloudflared 2021.1.1 in windows **without providing a logfile in the configuration** yields the error that you mentioned (`Falling back to a default logger due to logger setup failure:
mkdir : The system cannot find the path specified.`).
We will definitely look into that (which seems to be windows specific from what we've seen).

You do mention in the issue title that `2021.1.1 doesn't log to specified log file anymore`?
I've also just confirmed that if you do provide the `logfile` property, and pass that configuration to cloudflared (via `--config`) then cloudflared works fine and does print to the log (there seems to be some formatting issues with the terminal printing in windows, which we will also investigate).

**Comment by vidarak** [comment]
A tunnel list command shouldn't log anything or give errors like that.

**Comment by nmldiegues** [comment]
I appreciate the feedback @vidarak 

We will issue a `2021.1.2` soon that will address the problems mentioned above. Unfortunately they are windows specific, but we're on top of them now.


> When executing cloudflared.exe with -config parameter it managed to create the log file, but the log file is now JSON format instead of the old format

This was on purpose: 2021.X changed the way logging works (see https://github.com/cloudflare/cloudflared/commit/870f5fa907cdfc95afd0f156800be121feacf4be and other follow up commits) to **use structured logging**.
It's still human readable, but it is also machine parseable (which the previous logs were not).

**Comment by vidarak** [comment]
The updated didn't solve anything for me except removing the malplaced error message when running tunnel list. 
While running cloudflared as a windows service using all default service parameters it creates the cloudflared.log file in c:\windows\system32 but doesn't write anything to it.
While running cloudflared in cmd.exe as SYSTEM it now outputs to console in a nice colored way AND logs to the path specified in config.

**Comment by nmldiegues** [comment]
@vidarak  thank you for reporting this

You are now mentioning 2 problems:
 1. running as a service is not logging to the expected `logfile` configured;  I confirm that problem. However, I cannot confirm that "nothing is written to it", as in my tests (including in Windows) I see the C:\Windows\System32\<filenamechosen.log> being populated
 2. It is the first time that we hear about the retries parameter not being picked up. I have reproduced it, and apparently that was a regression back in November 2020. We will also address it. As a temporary workaround you can define the retries in the command that starts cloudflared. E.g., `cloudflared tunnel --config <somepath> --retries 10 run`

**Comment by vidarak** [comment]
1. It shouldn't create the file or write anything to c:\windows\system32 as I have defined a custom log file location (full path)
    I haven't tried to run as a Windows service WITHOUT having a log file define din my config. I do have it defined in my config and while running as a service the defined location is ignored and it instead creates the file in system32. Sysinternals Process Monitor shows the creation of the file but does not show any write attempts to it by the cloudflared.exe process while running as a windows service.
2. I reported this on my enterprise support ticket a while ago

**Comment by nmldiegues** [comment]
Totally understand that's not how it is supposed to work.

`2021.1.3` is coming out and those problems were addressed in it

**Comment by vidarak** [comment]
We're making progress. Now it creates the specified log file in the right location but it still doesn't write to it.

**Comment by nmldiegues** [comment]
I've managed to reproduce what you are observing:
 - running as a command cli, logging works fine everywhere I tested
 - running as a windows service, logging works fine with the log in some folder (I chose the Downloads folder)
 - running as a windows service, logging to another folder (my Home folder), the file gets created but not populated --- until the service is shut down (at which point all the logs are flushed there)

As a temporary workaround, can you place the log in the same folder as where cloudflared binary is to see if it helps?

This one seems less obvious to figure out.

**Comment by vidarak** [comment]
My cloudflared.exe is already in the same folder as the desired log file (c:\cloudflared).

**Comment by nmldiegues** [comment]
The good news is that we've figured this one out as well @vidarak , so we'll push out a release soon with it
Again, apologies for the process, but let's try to get a successful outcome out of this

**Comment by nmldiegues** [comment]
2021.1.4 is out, please give it a try

**Comment by vidarak** [comment]
It still doesn't write to the log while running as a service. When I stop the service it doesn't flush to the log either.

**Comment by nmldiegues** [comment]
> It still doesn't write to the log while running as a service. When I stop the service it doesn't flush to the log either.

This is running with 2021.1.4 for sure?

I have a setup with:
```
credentials-file: C:\Users\...\Downloads\UUID.json
hello-world: true
logfile: C:\Users\...\Downloads\output.log
```

I have installed the service and then modified the ImagePath in the Cloudflared service in the Registry, so that it does `C:\Users\...\Downloads\cloudflared.exe tunnel --config C:\Users\...\Downloads\config.yaml run`

With 2021.1.4 I am getting the logs in `C:\Users\...\Downloads\output.log` consistently and with no problems.

**Comment by vidarak** [comment]
Yes. i'm using all defaults for the service install with config/tokens in their default locations and binary+log in c:\cloudflared

**Comment by vidarak** [comment]
i'm using debug log level by the way:

logfile: c:\cloudflared\cloudflared.log
retries: 99
loglevel: debug

**Comment by nmldiegues** [comment]
It does not seem I can reproduce it anymore. I used exactly your settings (same file locations, same config) and it logs fine.

**Comment by vidarak** [comment]
I can reproduce on multiple systems here across multiple OS versions (Win10, Win2012R2, Win2019). 

```
name: MYSERVERNAME
logfile: c:\cloudflared\cloudflared.log
retries: 99
loglevel: debug

ingress:
  - service: hello_world
```

**Comment by vidarak** [comment]
The difference between 2020.11.11 and 2021.1.4 is that the openresult for the former is "Created" while the openresult for the latter is "opened". You're creating the file the wrong way I guess.
(getting this from Process Monitor as usual).

Desired Access:	Append Data/Add Subdirectory/Create Pipe Instance, Read Attributes, Synchronize
Disposition:	Open
Options:	Synchronous IO Non-Alert, Non-Directory File
Attributes:	N
ShareMode:	Read, Write
AllocationSize:	n/a
OpenResult:	Opened


Desired Access:	Append Data/Add Subdirectory/Create Pipe Instance, Read Attributes, Synchronize
Disposition:	OpenIf
Options:	Synchronous IO Non-Alert, Non-Directory File
Attributes:	N
ShareMode:	Read, Write
AllocationSize:	0
OpenResult:	Created

**Comment by vidarak** [comment]
![1](https://user-images.githubusercontent.com/4713602/104632936-b1a2f380-569e-11eb-8f3b-053ff9524f0e.png)
![2](https://user-images.githubusercontent.com/4713602/104632940-b23b8a00-569e-11eb-8afa-93468d3cfeb1.png)

Difference between 2020.11.11 and 2021.1.4 as seen by procmon when filtering for path ending with "cloudflared.log". Clearly in the latter case the process is not even attempting to write to the file.

**Comment by vidarak** [comment]
I'm seeing the same file handling (Open Reparse Point) when running 2021.1.4 from command prompt as 2020.11.11 does when successfully writing to log when running as service. Only when 2021.1.4 runs as a service opens the file differently.

**Comment by nmldiegues** [comment]
Thank you for all those details @vidarak 
We'll have to work further on reproducing this, because so far no luck.

As you can see next, the service that I set up above in the same way as you have, is writing to the file:

![Uploading image.png…]()

**Comment by nmldiegues** [comment]
Hello @vidarak 
It took us some funny fringe investigations, but we got there. **2021.1.5** was just released with all the problems discussed above fixed.

Thank you for the patience it took to get here.

**Comment by vidarak** [comment]
That solved it.
Not sure if it was intended, but now I'm spammed with entries like this (didn't use to have these useless 0 byte entries):
{"level":"debug","time":"2021-01-18T21:46:46+01:00","message":"mux - metrics: Outbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:46+01:00","message":"mux - metrics: Inbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:47+01:00","message":"mux - metrics: Outbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:47+01:00","message":"mux - metrics: Inbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:47+01:00","message":"mux - metrics: Inbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:47+01:00","message":"mux - metrics: Outbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:47+01:00","message":"mux - metrics: Outbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:47+01:00","message":"mux - metrics: Inbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:47+01:00","message":"mux - metrics: Inbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:47+01:00","message":"mux - metrics: Outbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:48+01:00","message":"mux - metrics: Inbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:48+01:00","message":"mux - metrics: Outbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:48+01:00","message":"mux - metrics: Inbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:48+01:00","message":"mux - metrics: Inbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:48+01:00","message":"mux - metrics: Outbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:48+01:00","message":"mux - metrics: Outbound bytes 0"}
{"level":"debug","time":"2021-01-18T21:46:48+01:00","message":"mux - metrics: Outbound bytes 0"}

**Comment by nmldiegues** [comment]
@vidarak  I will check what led to that.

Regardless, if you are using named tunnels (which is advised), then you can enable `protocol: http2` in your configuration, and those will be gone, since they are from the old h2mux protocol.

**Comment by adamchalmers** [comment]
Hi, we figured out where all those extra logs are coming from. They should be controlled by the `transport-loglevel` flag but they're mistakenly being controlled by the regular `loglevel` flag.

**Comment by adamchalmers** [comment]
Log verbosity is now fixed on master, it'll be released under 2021.2.1
