### ISSUE TITLE
QUIC not responding to requests

### ISSUE THREAD

**Issue by gvccvwangmingn2** [cloudflare/cloudflared#473]
I'm currently trying to reproduce the issue I've been experiencing #450 by using other protocols than http2, and noticed that you added quic support. 

I added ```-p quic``` to my cloudflared arguments, but when started (running 2021.9.1), requests are not coming through unless exit signal is given.

Does it actually work? or still in dev? 😅

```
2021-09-21T16:35:09Z INF Initial protocol quic
2021-09-21T16:35:09Z INF Starting metrics server on 127.0.0.1:37103/metrics
2021-09-21T16:35:09Z DBG edgediscovery - GetAddr: Giving connection its new address connIndex=0
2021-09-21T16:35:09Z DBG rpcconnect: tx (bootstrap = (questionId = 0, deprecatedObjectId = <opaque pointer>))
2021-09-21T16:35:09Z DBG rpcconnect: tx (call = (questionId = 1, target = (promisedAnswer = (questionId = 0, transform = [])), interfaceId = 17804583019846587543, methodId = 0, allowThirdPartyTailCall = false, params = (content = <opaque pointer>, capTable = []), sendResultsTo = (caller = void)))
2021-09-21T16:35:09Z DBG rpcconnect: rx (return = (answerId = 0, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [(senderHosted = 0)])))
2021-09-21T16:35:09Z DBG rpcconnect: tx (finish = (questionId = 0, releaseResultCaps = false))
2021-09-21T16:35:09Z DBG rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))
2021-09-21T16:35:09Z DBG rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))
2021-09-21T16:35:09Z INF Connection dfd2bbf1-0d08-42f7-b2e5-71151f57b112 registered connIndex=0 location=EWR
2021-09-21T16:35:09Z DBG edgediscovery - GetDifferentAddr: Giving connection its new address connIndex=1
2021-09-21T16:35:10Z DBG rpcconnect: tx (bootstrap = (questionId = 0, deprecatedObjectId = <opaque pointer>))
2021-09-21T16:35:10Z DBG rpcconnect: tx (call = (questionId = 1, target = (promisedAnswer = (questionId = 0, transform = [])), interfaceId = 17804583019846587543, methodId = 0, allowThirdPartyTailCall = false, params = (content = <opaque pointer>, capTable = []), sendResultsTo = (caller = void)))
2021-09-21T16:35:10Z DBG rpcconnect: rx (return = (answerId = 0, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [(senderHosted = 0)])))
2021-09-21T16:35:10Z DBG rpcconnect: tx (finish = (questionId = 0, releaseResultCaps = false))
2021-09-21T16:35:10Z DBG rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))
2021-09-21T16:35:10Z DBG rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))
2021-09-21T16:35:10Z INF Connection 4e2a593d-ef14-41ca-9f7f-fd36c4571a52 registered connIndex=1 location=ORD
2021-09-21T16:35:10Z DBG edgediscovery - GetDifferentAddr: Giving connection its new address connIndex=2
2021-09-21T16:35:11Z DBG rpcconnect: tx (bootstrap = (questionId = 0, deprecatedObjectId = <opaque pointer>))
2021-09-21T16:35:11Z DBG rpcconnect: tx (call = (questionId = 1, target = (promisedAnswer = (questionId = 0, transform = [])), interfaceId = 17804583019846587543, methodId = 0, allowThirdPartyTailCall = false, params = (content = <opaque pointer>, capTable = []), sendResultsTo = (caller = void)))
2021-09-21T16:35:11Z DBG rpcconnect: rx (return = (answerId = 0, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [(senderHosted = 0)])))
2021-09-21T16:35:11Z DBG rpcconnect: tx (finish = (questionId = 0, releaseResultCaps = false))
2021-09-21T16:35:11Z DBG rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))
2021-09-21T16:35:11Z DBG rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))
2021-09-21T16:35:11Z INF Connection b886ec73-9b52-453f-94f3-a504c04a02d2 registered connIndex=2 location=ORD
2021-09-21T16:35:11Z DBG edgediscovery - GetDifferentAddr: Giving connection its new address connIndex=3
2021-09-21T16:35:12Z DBG rpcconnect: tx (bootstrap = (questionId = 0, deprecatedObjectId = <opaque pointer>))
2021-09-21T16:35:12Z DBG rpcconnect: tx (call = (questionId = 1, target = (promisedAnswer = (questionId = 0, transform = [])), interfaceId = 17804583019846587543, methodId = 0, allowThirdPartyTailCall = false, params = (content = <opaque pointer>, capTable = []), sendResultsTo = (caller = void)))
2021-09-21T16:35:12Z DBG rpcconnect: rx (return = (answerId = 0, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [(senderHosted = 0)])))
2021-09-21T16:35:12Z DBG rpcconnect: tx (finish = (questionId = 0, releaseResultCaps = false))
2021-09-21T16:35:12Z DBG rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))
2021-09-21T16:35:12Z INF Connection a806c642-c9eb-4313-be2d-0e6b29078993 registered connIndex=3 location=IAD
2021-09-21T16:35:12Z DBG rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))

exit signal command CTRL+C

^C2021-09-21T16:35:53Z INF Initiating graceful shutdown due to signal interrupt ...
2021-09-21T16:35:53Z DBG rpcconnect: tx (call = (questionId = 1, target = (importedCap = 0), interfaceId = 17804583019846587543, methodId = 1, allowThirdPartyTailCall = false, params = (content = <opaque pointer>, capTable = []), sendResultsTo = (caller = void)))
2021-09-21T16:35:53Z DBG rpcconnect: tx (call = (questionId = 1, target = (importedCap = 0), interfaceId = 17804583019846587543, methodId = 1, allowThirdPartyTailCall = false, params = (content = <opaque pointer>, capTable = []), sendResultsTo = (caller = void)))
2021-09-21T16:35:53Z DBG rpcconnect: tx (call = (questionId = 1, target = (importedCap = 0), interfaceId = 17804583019846587543, methodId = 1, allowThirdPartyTailCall = false, params = (content = <opaque pointer>, capTable = []), sendResultsTo = (caller = void)))
2021-09-21T16:35:53Z DBG Graceful shutdown signalled
2021-09-21T16:35:53Z DBG rpcconnect: tx (call = (questionId = 1, target = (importedCap = 0), interfaceId = 17804583019846587543, methodId = 1, allowThirdPartyTailCall = false, params = (content = <opaque pointer>, capTable = []), sendResultsTo = (caller = void)))
2021-09-21T16:35:53Z DBG rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))
2021-09-21T16:35:53Z INF Unregistered tunnel connection connIndex=2
2021-09-21T16:35:53Z DBG rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))
2021-09-21T16:35:53Z DBG rpcconnect: rx error: context canceled
2021-09-21T16:35:53Z DBG rpcconnect: tx (abort = (reason = "rpc: shutdown", type = failed, obsoleteIsCallersFault = false, obsoleteDurability = 0))
2021-09-21T16:35:53Z DBG rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))
2021-09-21T16:35:53Z INF Unregistered tunnel connection connIndex=0
2021-09-21T16:35:53Z DBG rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))
2021-09-21T16:35:53Z DBG rpcconnect: rx error: context canceled
2021-09-21T16:35:53Z DBG rpcconnect: tx (release = (id = 0, referenceCount = 1))
2021-09-21T16:35:53Z DBG rpcconnect: tx (abort = (reason = "rpc: shutdown", type = failed, obsoleteIsCallersFault = false, obsoleteDurability = 0))
2021-09-21T16:35:53Z DBG rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))
2021-09-21T16:35:53Z INF Unregistered tunnel connection connIndex=1
2021-09-21T16:35:53Z DBG rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))
2021-09-21T16:35:53Z DBG rpcconnect: rx error: context canceled
2021-09-21T16:35:53Z DBG rpcconnect: tx (release = (id = 0, referenceCount = 1))
2021-09-21T16:35:53Z DBG rpcconnect: tx (abort = (reason = "rpc: shutdown", type = failed, obsoleteIsCallersFault = false, obsoleteDurability = 0))
2021-09-21T16:35:53Z DBG CF-RAY: 6924b4e4a8a5357f-SIN GET https://test.domain.com/ HTTP/1.1
2021-09-21T16:35:53Z DBG Inbound request CF-RAY=6924b4e4a8a5357a-SIN Header="map[Accept-Encoding:[gzip] Cdn-Loop:[cloudflare] Cf-Connecting-Ip:[xxx] Cf-Int-Tunnel-Request:[{\"account_id\":xxx}] Cf-Ipcountry:[ID] Cf-Ray:[6924b4e4a8a5357a-SIN] Cf-Visitor:[{\"scheme\":\"https\"}] Cf-Warp-Tag-Id:[xxx] Sec-Websocket-Key:[4fvJEUysdbA/U14xCJLVFA==] Sec-Websocket-Version:[13] User-Agent:[Go-http-client/1.1] X-Forwarded-For:[xxx] X-Forwarded-Proto:[https]]" host=test.domain.com path=/ rule=0
2021-09-21T16:35:53Z DBG CF-RAY: 6924b4e4a8a5357f-SIN Request content length 0
2021-09-21T16:35:53Z DBG rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))
2021-09-21T16:35:53Z INF Unregistered tunnel connection connIndex=3
2021-09-21T16:35:53Z DBG rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))
2021-09-21T16:35:53Z DBG rpcconnect: rx error: context canceled
2021-09-21T16:35:53Z DBG rpcconnect: tx (abort = (reason = "rpc: shutdown", type = failed, obsoleteIsCallersFault = false, obsoleteDurability = 0))
```

**Comment by sudarshan-reddy** [comment]
Hey @gvccvwangmingn2 thanks so much for reporting this. `quic` protocol should now work though some parts are continued to be worked on. 

What happens when the exit signal is given? Where do you have to give it?

**Comment by gvccvwangmingn2** [comment]
> Hey @gvccvwangmingn2 thanks so much for reporting this. `quic` protocol should now work though some parts are continued to be worked on.
> 
> What happens when the exit signal is given? Where do you have to give it?

So when the tunnel is running, I sent requests to the tunnel, but as you can see from logs, there are no incoming requests at all. So on client side, it is actually waiting for response from tunnel.

When I give exit signal (this is random, no exact seconds/minutes), then the incoming requests started coming in (2021-09-21T16:35:53Z), but it's too late.

**Comment by sudarshan-reddy** [comment]
Can I ask for a sample origin and request to reproduce this? It will help me find the issue faster.

**Comment by gvccvwangmingn2** [comment]
> Can I ask for a sample origin service and request you're using to reproduce this? It will help me find the issue faster.

I have a cloudflared running in session, so you can test it anytime, you can access it to https://test.servermantap.net

Current configuration is http (so can access directly from browser), running quic, v2021.9.1, have verified that the web server is running (if it works, you'll see a not found page)

**Comment by gvccvwangmingn2** [comment]
@sudarshan-reddy Did it work? I noticed requests coming in when I closed the tunnel (sent ctrl+c signal). This is what I see:

```
2021-09-22T12:02:09Z DBG rpcconnect: tx (release = (id = 0, referenceCount = 1))
2021-09-22T12:02:09Z DBG rpcconnect: tx (abort = (reason = "rpc: shutdown", type = failed, obsoleteIsCallersFault = false, obsoleteDurability = 0))
2021-09-22T12:02:09Z DBG CF-RAY: 6929f592ecfc4e08-FRA GET https://test.servermantap.net/ HTTP/1.1
2021-09-22T12:02:09Z DBG CF-RAY: 69294481cf565d33-LIS GET https://test.servermantap.net/ HTTP/1.1
2021-09-22T12:02:09Z DBG Inbound request CF-RAY=6929f592ecfc4e08-FRA Header="map[Accept-Encoding:[gzip] Cdn-Loop:[cloudflare] Cf-Connecting-Ip:[179.61.175.179] Cf-Int-Tunnel-Request:[{\"account_id\":36432529}] Cf-Ipcountry:[DE] Cf-Ray:[6929f592ecfc4e08-FRA] Cf-Visitor:[{\"scheme\":\"https\"}] Cf-Warp-Tag-Id:[8442f09c-3e82-4fa3-8174-e8a6fd520c49] Proxy-Authorization:[Basic bHVtLWN1c3RvbWVyLWNfNjY2NmRkYWYtem9uZS16b25lMjp5emt3dHZmZWd2cWM=] Referer:[http://test.servermantap.net] User-Agent:[Go-http-client/1.1] X-Forwarded-For:[179.61.175.179] X-Forwarded-Proto:[https]]" host=test.servermantap.net path=/ rule=0
2021-09-22T12:02:09Z DBG CF-RAY: 6929f592ecfc4e08-FRA Request content length 0
2021-09-22T12:02:09Z DBG Inbound request CF-RAY=69294481cf565d33-LIS Header="map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8] Accept-Encoding:[gzip] Accept-Language:[en-sg] Cdn-Loop:[cloudflare] Cf-Connecting-Ip:[2001:8a0:6a5f:8001:f15d:3588:ecd9:96d1] Cf-Int-Tunnel-Request:[{\"account_id\":36432529}] Cf-Ipcountry:[PT] Cf-Ray:[69294481cf565d33-LIS] Cf-Visitor:[{\"scheme\":\"https\"}] Cf-Warp-Tag-Id:[8442f09c-3e82-4fa3-8174-e8a6fd520c49] User-Agent:[Mozilla/5.0 (iPhone; CPU iPhone OS 14_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/93.0.4577.78 Mobile/15E148 Safari/604.1] X-Forwarded-For:[2001:8a0:6a5f:8001:f15d:3588:ecd9:96d1] X-Forwarded-Proto:[https]]" host=test.servermantap.net path=/ rule=0
2021-09-22T12:02:09Z DBG CF-RAY: 69294481cf565d33-LIS Request content length 0
2021-09-22T12:02:09Z DBG rpcconnect: rx (return = (answerId = 0, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [(senderHosted = 0)])))
2021-09-22T12:02:09Z DBG rpcconnect: tx (finish = (questionId = 0, releaseResultCaps = false))
2021-09-22T12:02:09Z DBG rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))
2021-09-22T12:02:09Z INF Connection 47134cab-aca2-4b0f-a687-862172d599d0 registered connIndex=0 location=ORD
2021-09-22T12:02:09Z DBG rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))
2021-09-22T12:02:09Z DBG rpcconnect: tx (call = (questionId = 1, target = (importedCap = 0), interfaceId = 17804583019846587543, methodId = 1, allowThirdPartyTailCall = false, params = (content = <opaque pointer>, capTable = []), sendResultsTo = (caller = void)))
2021-09-22T12:02:09Z DBG rpcconnect: rx (return = (answerId = 0, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [(senderHosted = 0)])))
2021-09-22T12:02:09Z DBG rpcconnect: tx (finish = (questionId = 0, releaseResultCaps = false))
2021-09-22T12:02:09Z DBG rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))
2021-09-22T12:02:09Z DBG rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))
2021-09-22T12:02:09Z INF Connection 96f33977-4883-4016-8f7c-853a996219c5 registered connIndex=1 location=ORD
2021-09-22T12:02:09Z DBG rpcconnect: tx (call = (questionId = 1, target = (importedCap = 0), interfaceId = 17804583019846587543, methodId = 1, allowThirdPartyTailCall = false, params = (content = <opaque pointer>, capTable = []), sendResultsTo = (caller = void)))
2021-09-22T12:02:09Z DBG rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))
2021-09-22T12:02:09Z INF Unregistered tunnel connection connIndex=0
2021-09-22T12:02:09Z DBG rpcconnect: rx error: context canceled
2021-09-22T12:02:09Z DBG rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))
2021-09-22T12:02:09Z DBG rpcconnect: tx (release = (id = 0, referenceCount = 1))
2021-09-22T12:02:09Z DBG rpcconnect: tx (abort = (reason = "rpc: shutdown", type = failed, obsoleteIsCallersFault = false, obsoleteDurability = 0))
2021-09-22T12:02:10Z DBG rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))
2021-09-22T12:02:10Z INF Unregistered tunnel connection connIndex=1
2021-09-22T12:02:10Z DBG rpcconnect: rx error: context canceled
2021-09-22T12:02:10Z DBG rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))
2021-09-22T12:02:10Z DBG rpcconnect: tx (release = (id = 0, referenceCount = 1))
2021-09-22T12:02:10Z DBG rpcconnect: tx (abort = (reason = "rpc: shutdown", type = failed, obsoleteIsCallersFault = false, obsoleteDurability = 0))
```

I restarted the tunnel, so you can test things out again

**Comment by sudarshan-reddy** [comment]
Yes that was me. I was more interested in seeing how your origin service is written so I can reproduce (and fix ;) ) it in my lab. 

Can you give me a very barebones hello world server that you can find this?

I ask because my examples all work and an example would speed things up.

**Comment by gvccvwangmingn2** [comment]
> Yes that was me. I was more interested in seeing how your origin service is written so I can reproduce (and fix ;) ) it in my lab.
> 
> Can you give me a very barebones hello world server that you can find this?
> 
> I ask because my examples all work and an example would speed things up.

Sure, this is origin service (simple http, using nodejs)
```js
const express = require('express')

const app = express()

app.get('/', (req, res) => {
        res.status(200).send({message: 'OK'})
})

app.listen(3000)
```

I ran cloudflared without any config, just arguments directly:
```
./cloudflared tunnel --loglevel debug run --url http://localhost:3000 --protocol quic test
```

If it works on your environment, I wonder if it's my server/network acting up.. but no indication/errors about that (yet)

**Comment by sudarshan-reddy** [comment]
@gvccvwangmingn2 : Just to confirm, can you try this with cloudflared version `2021.8.7`?

**Comment by gvccvwangmingn2** [comment]
> @gvccvwangmingn2 : Just to confirm, can you try this with cloudflared version `2021.8.7`?

Yup, it works in 2021.8.7. You can try it too, the tunnel is running 2021.8.7

**Comment by sudarshan-reddy** [comment]
Thanks for reporting this @gvccvwangmingn2 . I'll work on this and get a fix out soon. Meanwhile stay awesome and thanks for catching these super early.

**Comment by sudarshan-reddy** [comment]
Fixed by https://github.com/cloudflare/cloudflared/commit/27e1277a3b171caf5710b72cf9416be4dc73270b. 

Upgrade to release `2021.9.2` to use `cloudflared` with `quic` protocol and this problem will have been fixed.

**Comment by bompus** [comment]
In `2021.9.2` ,  I'm still not able to get a connection through the tunnel at all using protocol: quic ( in a tunnel config file ), it just eventually times out.

Can you try it as well @gvccvwangmingn2 and report your findings?

**Comment by sudarshan-reddy** [comment]
Can you show me your cloudflared logs please?

**Comment by bompus** [comment]
I'm running on Ubuntu 20.04.3 LTS with kernel 5.11.0-34-generic under VMware with Windows 10 as the host.

`cloudflared tunnel --config tunnel.yml --metrics 127.0.0.1:9001 run`

I'm attaching the config and log files for both protocol: quic and protocol: http2 config options. From reviewing the diffs, I already see some differences, and the likely cause for protocol: quic not connecting ( bullet point 2 below ).

[tunnel.yml.txt](https://github.com/cloudflare/cloudflared/files/7254094/tunnel.yml.txt)
[protocol-quic-log.txt](https://github.com/cloudflare/cloudflared/files/7254095/protocol-quic-log.txt)
[protocol-http2-log.txt](https://github.com/cloudflare/cloudflared/files/7254096/protocol-http2-log.txt)

My observations:

1. With protocol: http2, the log file has connIndex lines for "Connecting via http2", but these lines are not present when using protocol: quic. I would expect it to log "Connecting via quic" for consistency.
2. With protocol: http2, it tries to `GET http://localhost:8080/dashboard/api/core/health/` , but with protocol: quic, it tries to `GET https://cmslocal.censored-domain.com/dashboard/api/core/health/` 
3. With protocol: http2, the GET line declares HTTP/2.0 , but with quic, it declares HTTP/1.1. I believe protocol: http2 is actually incorrect here, as it shouldn't be trying to use HTTP/2.0 to an http:// ingress. Apart from that, I didn't think cloudflared supported http/2 to the ingress anyway, so I believe this should always be HTTP/1.1 regardless of protocol: http2 or protocol: quic.
4. With protocol: http2, I see Early-Data:[1] in the CF-RAY log line, but I don't see this in the protocol: quic log file.
5. With protocol: http2, the response is sent and returned from the ingress, `Status: 200 OK served by ingress`, but the request is never sent to the ingress with protocol: quic, likely due to bullet point (2), it appears to be trying to connect internally to the tunneled `https://cmslocal.censored-domain.com` instead of the expected ingress rule `http://localhost:8080`

**Comment by gvccvwangmingn2** [comment]
@bompus, not seeing any issues with 2021.9.2, am able to use quic and receive requests correctly. I'll try to check further soon.

**Comment by sudarshan-reddy** [comment]
Thanks for this detailed summary @bompus. I'm going to take a look at it. Feel free to open this ticket or create a new one while you wait on me.
