### ISSUE TITLE
🐛Intermittent outages

### ISSUE THREAD

**Issue by gzheng92** [cloudflare/cloudflared#694]
**Describe the bug**
I have a Cloudflare tunnel set up.  Recently (maybe related to updating to 2022.7.1?) the tunnel disconnects from all four connections, preventing me from connecting at all.  If I restart Cloudflare it works again, but goes down after a random amount of time.  I suspect it's related to
- quic
- china firewall (the server is in China)

**To Reproduce**
1. Very basic Cloudflare tunnel config (the same config works on 2 other machines outside of China with no issue)
2. Verify ports are fine as per https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ports-and-ips/ (all tests report no errors)
3. Run Cloudflared as a system service, tunnel works upon start / restart
4. After a few hours, the tunnel goes down
5. I get these errors in the log file (for all 4 active connections):
```
ERR Failed to create new quit connection error="failed to dial to edge with quick: timeout: no recent network activity" connIndex=2
ERR Connection terminated error="failed to dial to edge with quick: timeout: no recent network activity" connIndex=2
```

**Expected behavior**
I expect the tunnel to go up and stay up barring exceptional circumstances

**Environment and versions**
 - OS: Ubuntu 20.04
 - Architecture: x64
 - Version: 2022.07.1

**Logs and errors**
Logs included above.

**Additional context**
As I said, server is in China so it might be a GFW issue.  However, the tunnel was quite stable up until this month, so it might be related to 2022.7.1.  As a bandaid, I'm trying high values for Connection Timeout and Idle Connection Expiration Time, but doubling those to 60 and 60 didn't resolve the issue.

**Comment by sudarshan-reddy** [comment]
Hey @gzheng92 ! Are you sure you have UDP egress from this machine?

**Comment by cwegener** [comment]
I think I may have hit this problem myself as well after upgrading to 2022.7.1

All connections die and the `cloudflared` tunnel process needs to be restarted in order to restore the tunnel connectivity.

There is no firewall (only a NAT router) between my origin and the CF edge.

I've just now restarted `cloudflared` on an affected origin server and am just watching the logs to see if the issue comes back.

**Comment by sudarshan-reddy** [comment]
I see. Can you see if your cloudflared is falling back to an http2 connection?

**Comment by sudarshan-reddy** [comment]
You should have likely had this bug with `2022.7.0`. We fixed the fall back on `2022.7.1`. 

Glad to hear your problem is fixed. Feel free to open an issue if you have further issues. (And perhaps give QUIC a try too since it's going to be our stable protocol going forwards!)

**Comment by Manouchehri** [comment]
I was still facing this issue with 2022.7.1, but it appears 2022.8.0 might have resolved it. =)

**Comment by sudarshan-reddy** [comment]
That comment itself doesn't give us any details. Can you please give us a a detailed description of whats happening and what your setup is like? And preferably open a new issue?

**Comment by Manouchehri** [comment]
Sure, I can open a new issue. The description of the problem is exactly the same though, the QUIC tunnel goes down after what appears to be a random ish amount of time. Restarting cloudflared manually seems to allow QUIC to work again (which doesn't really make sense).

```
Aug 11 13:15:47 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:15:47Z INF Connection REMOVED1 registered connIndex=3 ip=198.41.192.227 location=MSP
Aug 11 13:35:02 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:02Z INF Unregistered tunnel connection connIndex=1
Aug 11 13:35:02 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:02Z WRN Failed to serve quic connection error="failed to accept QUIC stream: timeout: no recent network activity" connIndex=1 ip=198.41.192.57
Aug 11 13:35:03 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:03Z WRN Serve tunnel error error="failed to accept QUIC stream: timeout: no recent network activity" connIndex=1 ip=198.41.192.57
Aug 11 13:35:03 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:03Z INF Retrying connection in up to 1s seconds connIndex=1 ip=198.41.192.57
Aug 11 13:35:03 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:03Z INF Unregistered tunnel connection connIndex=3
Aug 11 13:35:03 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:03Z WRN Failed to serve quic connection error="failed to accept QUIC stream: timeout: no recent network activity" connIndex=3 ip=198.41.192.227
Aug 11 13:35:03 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:03Z WRN Serve tunnel error error="failed to accept QUIC stream: timeout: no recent network activity" connIndex=3 ip=198.41.192.227
Aug 11 13:35:03 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:03Z INF Retrying connection in up to 1s seconds connIndex=3 ip=198.41.192.227
Aug 11 13:35:04 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:04Z WRN If this log occurs persistently, and cloudflared is unable to connect to Cloudflare Network with `quic` protocol, then most likely your machine/network is getting its egress UDP to port 7844 (or others) blocked or dropped. Make sure to allow egress connectivity as per https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ports-and-ips/
Aug 11 13:35:04 dave-cloudflared-test-6 cloudflared[18309]: If you are using private routing to this Tunnel, then UDP (and Private DNS Resolution) will not work unless your cloudflared can connect with Cloudflare Network with `quic`. connIndex=3 ip=198.41.192.227
Aug 11 13:35:04 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:04Z INF Switching to fallback protocol http2 connIndex=3 ip=198.41.192.227
Aug 11 13:35:04 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:04Z WRN Connection terminated error="failed to accept QUIC stream: timeout: no recent network activity" connIndex=3
Aug 11 13:35:04 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:04Z WRN If this log occurs persistently, and cloudflared is unable to connect to Cloudflare Network with `quic` protocol, then most likely your machine/network is getting its egress UDP to port 7844 (or others) blocked or dropped. Make sure to allow egress connectivity as per https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ports-and-ips/
Aug 11 13:35:04 dave-cloudflared-test-6 cloudflared[18309]: If you are using private routing to this Tunnel, then UDP (and Private DNS Resolution) will not work unless your cloudflared can connect with Cloudflare Network with `quic`. connIndex=1 ip=198.41.192.57
Aug 11 13:35:04 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:04Z INF Switching to fallback protocol http2 connIndex=1 ip=198.41.192.57
Aug 11 13:35:04 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:04Z WRN Connection terminated error="failed to accept QUIC stream: timeout: no recent network activity" connIndex=1
Aug 11 13:35:21 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:21Z INF Connection REMOVED2 registered connIndex=3 ip=198.41.192.227 location=YYZ
Aug 11 13:35:21 dave-cloudflared-test-6 cloudflared[18309]: 2022-08-11T13:35:21Z INF Connection REMOVED3 registered connIndex=1 ip=198.41.192.57 location=EWR
```

**Comment by Manouchehri** [comment]
> Restarting cloudflared manually seems to allow QUIC to work again (which doesn't really make sense).

By "work", I mean cloudflared starts to use QUIC as the transport again without issue. (Instead of http2.)

**Comment by Manouchehri** [comment]
Just thought of something, doesn't `cloudflared --protocol=quic` already force-disable the http2 fallback? (I'm running with that now to see if anything changes.)

**Comment by Manouchehri** [comment]
Ah okay, so `--protocol=quic` is indeed a usable workaround for now. I'll open a new ticket for the other issue I think I see now.

**Comment by sudarshan-reddy** [comment]
Correct. It is a useable workaround indeed. But ideally, we don't want to fallback to http2 if we know quic has worked during the lifetime of this client before.

**Comment by cwegener** [comment]
Has there been any progress on solving the original issue?

I'm trying to figure out why this issue has been closed.

This issue has been causing me a lot of outages over the last two months.

**Comment by abelinkinbio** [comment]
@cwegener when you have a moment, would you mind opening a new bug ticket describing the issue with the errors/impact you're seeing?

**Comment by cwegener** [comment]
@abelinkinbio Yup. Will do. I'll try and do some tests that can produce the issue at will (since I normally have to wait for my upstream Internet provider to have an outage in order for the issue to occur, but I think I can simulate the upstream outage myself.)

**Comment by sudarshan-reddy** [comment]
This is the same as https://github.com/cloudflare/cloudflared/issues/698. A potential fix would be out soon.

**Comment by sudarshan-reddy** [comment]
https://github.com/cloudflare/cloudflared/commit/e3390fcb15c52a8e2a33fd9002680852b12e2f67 is the fix We'll make a release early next week. In the meantime if you want to test this or want this feature, feel free to build from source.

**Comment by cwegener** [comment]
Oh. That does sound very promising! I'll build from that commit over the weekend and do some testing on one of the origin machines that has been running into the issue consistently (due to the Internet upstream on that box going down for up to an hour at a time quite frequently)

**Comment by cwegener** [comment]
@sudarshan-reddy I tested commit e3390fc and now the backoff-retry proceeds beyond the previously capped 4 or 5 retry attempts, and the backoff timer then stays flat at 1m 4s.

This looks like an acceptable behaviour to me.

NOTE: I had to skip tests in order to build commit e3390fc, because after commit bad2e8e812d898c32b0aacc66a6f947109eaf24a tests are failing for me.

**Comment by sudarshan-reddy** [comment]
Thanks for checking @cwegener ! It’s a real delight when we have members of the community not only helpfully reporting problems but willing to beta test them. ❤️
