### ISSUE TITLE
problems installing cloudflared on ubuntu

### ISSUE THREAD

**Issue by samuelcolvin** [cloudflare/cloudflared#9]
Running ubuntu 18.04.

I tried to follow the instructions at [here](https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy/) however they didn't work

First I got an error installing the service:
```
~ 130 11.99s ➤  sudo cloudflared service install
INFO[0000] Applied configuration from /usr/local/etc/cloudflared/config.yaml 
INFO[0000] Failed to copy user configuration. Before running the service, ensure that /etc/cloudflared contains two files, cert.pem and config.yml  error="open /usr/local/etc/cloudflared/cert.pem: no such file or directory"
```

Which I fixed with `sudo cp /etc/cloudflared/cert.pem /usr/local/etc/cloudflared/cert.pem`

Then I got an error while starting the service, which included

    time="2018-04-09T11:51:57+01:00" level=info msg="Cannot load configuration from /etc/cloudflared/config.yml" error="Unable to load

Which I in turn fixed with with `sudo cp  /usr/local/etc/cloudflared/config.yaml /etc/cloudflared/config.yml`.

The service then runs fine.

Looking back on this I guess the overall problem is that `/usr/local/etc/cloudflared/` should actually be `/etc/cloudflared/` in the instructions, that would also avoid the `mkdir` command as `/etc/cloudflared/` already exists.

**Comment by sander1** [comment]
Same issue on Ubuntu 16.04. Creating file `/etc/cloudflared/config.yml` (not `.yaml`) fixed the issue.

**Comment by jauderho** [comment]
Correct. There are inconsistencies in the use of .yml vs. .yaml.

Executing "sudo cloudflared service install" copies the file as .yaml but the systemd definition refers to .yml

> user@a009:/usr/local/etc/cloudflared$  sudo cloudflared service install
INFO[0000] Applied configuration from /usr/local/etc/cloudflared/config.yaml 
INFO[0000] Copied /usr/local/etc/cloudflared/config.yaml to /etc/cloudflared/config.yaml 
INFO[0000] Using Systemd                                
ERRO[0000] systemctl: Created symlink /etc/systemd/system/multi-user.target.wants/cloudflared.service → /etc/systemd/system/cloudflared.service.
INFO[0000] systemctl daemon-reload                      
user@a009:/usr/local/etc/cloudflared$ sudo cat /etc/systemd/system/cloudflared.service
[Unit]
Description=Argo Tunnel
After=network.target
[Service]
TimeoutStartSec=0
Type=notify
ExecStart=/usr/local/bin/cloudflared --config /etc/cloudflared/config.yml --origincert /etc/cloudflared/cert.pem --no-autoupdate
Restart=on-failure
RestartSec=5s
[Install]
WantedBy=multi-user.target

**Comment by sssilver** [comment]
This problem has been resolved.

**Comment by NightRider0** [comment]
This is still an issue but in reverse on ubuntu 18.04 once I renamed config.yml to config.ymal it works just fine

**Comment by martin3000** [comment]
The documentation still has the wrong directory:
https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy/
