### ISSUE TITLE
Many http/2 tunnels on different servers are getting repeatedly disconnected  `Connection terminated error="connection with edge closed"`

### ISSUE THREAD

**Issue by pirate** [cloudflare/cloudflared#917]
**Describe the bug**

We're a software consultancy that uses many different hosting providers and platforms for a wide variety of client projects (AWS, DigitalOcean, Vultr, etc.). We use `cloudflared` tunnels for ingress for many of our apps, with probably 30+ tunnels running at any given time on servers around the world.

On March 9th, 2023 all of our Cloudflare tunnels disconnected around the same time. According to the Cloudflare admin dashboard audit log (see screenshot below), all of the tunnels were de-registered due to "origin server went away" or "opened elsewhere", and then re-registered. Most came up successfully after the outage on their own, but a few never successfully reconnected until we SSH'd in to restart the `cloudflared` container. They all showed lots of this error in console:

`Connection terminated error="connection with edge closed"` (which may be a red herring, or may be related, there are so many of these lines it's hard to tell if they're a cause or a symptom)

No one had changed anything in our Cloudflare config on March 9th (or even logged into the admin dash prior to the incident), and no one had logged into the servers affected via SSH either, so we're 99% sure we didn't do anything to trigger this. It also occurred across multiple hosting providers, so we don't think it was an outage on DigitalOcean or any one of our VPS providers.

...

On March 15th (edit: and again on March 16th), one of these tunnels randomly started experiencing this error again, causing a critical service to go down for several hours. Nothing has changed on this server during this time, and restarting it fixed it with seemingly no underlying cause and no other applications on the server affected. The server has plenty of memory, cpu, and bandwidth, and none of the other things on the server experienced packet loss when the tunnel went down.

We're worried this will keep happening and we'll have to move off Cloudflare entirely, but would really like to avoid that as tunnels are quite nice for one-line docker-based deployment without needing config files/admin dash setup/persistent state/etc.

**To Reproduce**
1. Run `cloudflared/cloudflared:2023.3.1` in docker on a DigitalOcean VPS
2. Wait ?
3. Tunnel randomly disconnects, restarting the tunnel container fixes it instantly

If it's an issue with Cloudflare Tunnel:
4. Tunnel ID: `2b2bd7dc-633f-4fae-b385-24423f0fbb9d`
5. cloudflared config: 

```yaml
argo:
    image: cloudflare/cloudflared:
    command: tunnel --no-autoupdate --overwrite-dns --retries 15 --protocol http2 --url http://hedgedoc:3000 --hostname docs.zervice.io --name docs.zervice.io
    volumes:
      # cert.pem in this folder from https://dash.cloudflare.com/argotunnel
      - ./etc/cloudflared:/etc/cloudflared
```

**Environment and versions**
 - OS: `Ubuntu 22.04.2`
 - Architecture: `amd64`
 - Version: `2023.3.1`

**Logs and errors**

```logs
argo_1      | 2023-03-16T05:08:01Z INF Connection 94991c9c-8a41-497e-897a-360734fd564c registered with protocol: http2 connIndex=0 ip=198.41.192.67 location=EWR
argo_1      | 2023-03-16T05:12:07Z INF Lost connection with the edge connIndex=0
argo_1      | 2023-03-16T05:12:07Z WRN Serve tunnel error error="connection with edge closed" connIndex=0 ip=198.41.192.67
argo_1      | 2023-03-16T05:12:07Z INF Unregistered tunnel connection connIndex=0
argo_1      | 2023-03-16T05:12:07Z INF Retrying connection in up to 1s connIndex=0 ip=198.41.192.67
argo_1      | 2023-03-16T05:12:08Z WRN Connection terminated error="connection with edge closed" connIndex=0
argo_1      | 2023-03-16T05:12:09Z INF Connection 3163ea84-9031-4033-8e65-a00e72f17759 registered with protocol: http2 connIndex=0 ip=198.41.192.67 location=EWR
argo_1      | 2023-03-16T05:14:03Z INF Unregistered tunnel connection connIndex=0
argo_1      | 2023-03-16T05:14:03Z INF Lost connection with the edge connIndex=0
argo_1      | 2023-03-16T05:14:03Z WRN Serve tunnel error error="connection with edge closed" connIndex=0 ip=198.41.192.67
argo_1      | 2023-03-16T05:14:03Z INF Retrying connection in up to 1s connIndex=0 ip=198.41.192.67
argo_1      | 2023-03-16T05:14:04Z WRN Connection terminated error="connection with edge closed" connIndex=0
argo_1      | 2023-03-16T05:14:12Z INF Connection 914121fc-04f4-4634-922e-3c464328c9dd registered with protocol: http2 connIndex=0 ip=198.41.192.67 location=EWR
argo_1      | 2023-03-16T05:14:34Z INF Lost connection with the edge connIndex=0
argo_1      | 2023-03-16T05:14:34Z WRN Serve tunnel error error="connection with edge closed" connIndex=0 ip=198.41.192.67
argo_1      | 2023-03-16T05:14:34Z INF Retrying connection in up to 1s connIndex=0 ip=198.41.192.67
argo_1      | 2023-03-16T05:14:34Z INF Unregistered tunnel connection connIndex=0
argo_1      | 2023-03-16T05:14:35Z WRN Connection terminated error="connection with edge closed" connIndex=0
argo_1      | 2023-03-16T05:14:44Z INF Connection 17872c64-60d8-43dc-bdfd-8e2b54a1034a registered with protocol: http2 connIndex=0 ip=198.41.192.67 location=EWR
```

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/511499/225522209-90b7c4d3-80d7-4b44-bf19-0b5ffeb63694.png">
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/511499/225523578-01cfc9a6-e53c-45fa-a107-38611cc496ac.png">
<img width="1413" alt="Screenshot 2023-03-16 at 10 25 13 AM" src="https://user-images.githubusercontent.com/511499/225687437-c7f58a19-0dfe-4b39-b4c8-6e799ada64ff.png">
<img width="1193" alt="Screenshot 2023-03-16 at 10 24 57 AM" src="https://user-images.githubusercontent.com/511499/225687346-777c5e51-7574-4154-81d9-375f8aa8e818.png">

**Comment by terabitti** [comment]
I have had similar experiences. Cloudflare Tunnel has been going worse and worse and I don't know what I could do about it other than to migrate away from it. Today it has been a nightmare.

I do have 5 servers with tunnels. Only 2 of them are dropping connections currently. One of them is dropping constantly and the other "only" every 15 minutes or so.

Server "A" is tunneling service www.example.com:80 (name changed) which is constantly losing connection. I tried to move tunneling of this service to server "B" (on the same network, sending http requests to the server A). After that the tunnel on the B started to drop connections and the tunnel on the A was good. Then switched back and the A started to drop connections and the B was good. So this issue followed with the service/domain.

I tried to ping some Cloudflare IP addresses and got 0% packet loss. I also can't find any other problem from my servers except that it just cloudflared which is dropping connections because "Lost connection with the edge" and 'Connection terminated error="connection with edge closed"'.

If this is just my server/service configuration, is there any info what I should to do to make cloudflared work better?

This is what happens all the time:

```
2023-03-16T14:51:58Z ERR Connection terminated error="connection with edge closed" connIndex=2
2023-03-16T14:54:35Z INF Connection dc1d923f-e423-4dd9-8980-458918aad271 registered with protocol: http2 connIndex=1 ip=198.41.200.63 location=HEL
2023-03-16T14:54:35Z INF Connection 0bc9e2bf-b6c1-4c3f-afb0-591089abfac9 registered with protocol: http2 connIndex=0 ip=198.41.192.27 location=FRA
2023-03-16T14:54:35Z INF Connection f78b3bf6-3ed2-4e42-8f8f-a1d26bc97e4e registered with protocol: http2 connIndex=2 ip=198.41.192.167 location=FRA
2023-03-16T14:54:35Z INF Connection 8b7e659d-9825-4055-acf5-b9c77d9f4600 registered with protocol: http2 connIndex=3 ip=198.41.200.113 location=HEL
2023-03-16T14:54:45Z INF Lost connection with the edge connIndex=3
2023-03-16T14:54:45Z WRN Serve tunnel error error="connection with edge closed" connIndex=3 ip=198.41.200.113
2023-03-16T14:54:45Z INF Retrying connection in up to 1s connIndex=3 ip=198.41.200.113
2023-03-16T14:54:45Z INF Unregistered tunnel connection connIndex=3
2023-03-16T14:54:46Z WRN Connection terminated error="connection with edge closed" connIndex=3
2023-03-16T14:55:37Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=7a8dd57ee81a0a44-ARN ingressRule=0 originService=http://www.example.com:80
2023-03-16T14:55:37Z ERR failed to serve incoming request error="Failed to proxy HTTP: Incoming request ended abruptly: context canceled"
2023-03-16T14:55:40Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=7a8dd5eb8f94c7da-TLL ingressRule=0 originService=http://www.example.com:80
```

Here you can see how often this happens:

```
2023-03-16T14:00:17Z INF Lost connection with the edge connIndex=1
2023-03-16T14:00:41Z INF Lost connection with the edge connIndex=0
2023-03-16T14:01:08Z INF Lost connection with the edge connIndex=2
2023-03-16T14:02:13Z INF Lost connection with the edge connIndex=0
2023-03-16T14:02:14Z INF Lost connection with the edge connIndex=1
2023-03-16T14:07:06Z INF Lost connection with the edge connIndex=3
2023-03-16T14:08:09Z INF Lost connection with the edge connIndex=2
2023-03-16T14:08:18Z INF Lost connection with the edge connIndex=1
2023-03-16T14:08:48Z INF Lost connection with the edge connIndex=0
2023-03-16T14:08:56Z INF Lost connection with the edge connIndex=3
2023-03-16T14:09:25Z INF Lost connection with the edge connIndex=2
2023-03-16T14:10:32Z INF Lost connection with the edge connIndex=1
2023-03-16T14:10:36Z INF Lost connection with the edge connIndex=0
2023-03-16T14:11:27Z INF Lost connection with the edge connIndex=1
2023-03-16T14:11:42Z INF Lost connection with the edge connIndex=0
2023-03-16T14:12:15Z INF Lost connection with the edge connIndex=3
2023-03-16T14:12:44Z INF Lost connection with the edge connIndex=2
2023-03-16T14:15:47Z INF Lost connection with the edge connIndex=3
2023-03-16T14:17:08Z INF Lost connection with the edge connIndex=3
2023-03-16T14:17:46Z INF Lost connection with the edge connIndex=2
2023-03-16T14:17:52Z INF Lost connection with the edge connIndex=0
2023-03-16T14:18:13Z INF Lost connection with the edge connIndex=3
2023-03-16T14:19:22Z INF Lost connection with the edge connIndex=3
2023-03-16T14:20:29Z INF Lost connection with the edge connIndex=2
2023-03-16T14:20:35Z INF Lost connection with the edge connIndex=0
2023-03-16T14:21:40Z INF Lost connection with the edge connIndex=1
2023-03-16T14:22:38Z INF Lost connection with the edge connIndex=0
2023-03-16T14:23:10Z INF Lost connection with the edge connIndex=2
2023-03-16T14:26:10Z INF Lost connection with the edge connIndex=3
2023-03-16T14:27:12Z INF Lost connection with the edge connIndex=2
2023-03-16T14:29:34Z INF Lost connection with the edge connIndex=1
2023-03-16T14:30:12Z INF Lost connection with the edge connIndex=0
...
```

**Comment by crackalak** [comment]
I have also come across this issue today.
We have 4 tunnels setup with 2 tunnels per Cloudflare Load Balancer. This morning at 02:13:17 UTC, both of the tunnels connected to the same Load Balancer started dropping connections.
Restarting cloudflared, when it got stuck at various times in the day, would solve the problem for a while. However, we are still getting disconnections, whilst the other 2 tunnels are running perfectly well.

```
2023-03-16T15:38:45Z INF Connection 3964d3a4-9a49-41ea-8c60-0b69f1d5eb3d registered connIndex=2 location=MAN
2023-03-16T15:38:49Z INF Lost connection with the edge connIndex=1
2023-03-16T15:38:50Z ERR Serve tunnel error error="connection with edge closed" connIndex=1
2023-03-16T15:38:50Z INF Retrying connection in up to 1s seconds connIndex=1
2023-03-16T15:38:50Z INF Unregistered tunnel connection connIndex=1
2023-03-16T15:38:51Z INF Connection 6c6001a4-e4c6-48df-83c8-c34f1f27061c registered connIndex=1 location=LHR
2023-03-16T15:39:31Z INF Lost connection with the edge connIndex=1
2023-03-16T15:39:31Z ERR Serve tunnel error error="connection with edge closed" connIndex=1
2023-03-16T15:39:31Z INF Retrying connection in up to 1s seconds connIndex=1
2023-03-16T15:39:31Z INF Unregistered tunnel connection connIndex=1
2023-03-16T15:39:31Z INF Connection 7639cecc-309c-4c3f-90bb-79f071705a19 registered connIndex=1 location=LHR
2023-03-16T15:41:35Z INF Lost connection with the edge connIndex=2
2023-03-16T15:41:35Z ERR Serve tunnel error error="connection with edge closed" connIndex=2
2023-03-16T15:41:35Z INF Retrying connection in up to 1s seconds connIndex=2
2023-03-16T15:41:35Z INF Unregistered tunnel connection connIndex=2
2023-03-16T15:41:36Z INF Connection 712bd754-a544-4278-980c-294211355e51 registered connIndex=2 location=MAN
2023-03-16T15:41:54Z INF Lost connection with the edge connIndex=0
2023-03-16T15:41:54Z INF Unregistered tunnel connection connIndex=0
2023-03-16T15:41:54Z ERR Serve tunnel error error="connection with edge closed" connIndex=0
2023-03-16T15:41:54Z INF Retrying connection in up to 1s seconds connIndex=0
2023-03-16T15:41:56Z INF Connection 2074d8a7-5085-4a3a-9cb8-a5027904ac1e registered connIndex=0 location=MAN
2023-03-16T15:42:21Z INF Lost connection with the edge connIndex=0
2023-03-16T15:42:21Z ERR Serve tunnel error error="connection with edge closed" connIndex=0
2023-03-16T15:42:21Z INF Retrying connection in up to 1s seconds connIndex=0
2023-03-16T15:42:21Z INF Unregistered tunnel connection connIndex=0
2023-03-16T15:42:23Z INF Connection 2f7b16ed-3923-4acf-a311-f7db26f1b74f registered connIndex=0 location=MAN
2023-03-16T15:42:35Z INF Lost connection with the edge connIndex=1
2023-03-16T15:42:35Z ERR Serve tunnel error error="connection with edge closed" connIndex=1
2023-03-16T15:42:35Z INF Unregistered tunnel connection connIndex=1
2023-03-16T15:42:35Z INF Retrying connection in up to 1s seconds connIndex=1
2023-03-16T15:42:37Z INF Connection 05d19c44-4f4b-49e5-af09-258aff52ca54 registered connIndex=1 location=LHR
2023-03-16T15:42:38Z INF Lost connection with the edge connIndex=2
2023-03-16T15:42:38Z ERR Serve tunnel error error="connection with edge closed" connIndex=2
2023-03-16T15:42:38Z INF Retrying connection in up to 1s seconds connIndex=2
2023-03-16T15:42:38Z INF Unregistered tunnel connection connIndex=2
2023-03-16T15:42:40Z INF Connection 21ef6af2-e65c-4e34-ade5-07e5d4b1f723 registered connIndex=2 location=MAN
2023-03-16T15:43:07Z INF Lost connection with the edge connIndex=1
2023-03-16T15:43:07Z ERR Serve tunnel error error="connection with edge closed" connIndex=1
2023-03-16T15:43:07Z INF Retrying connection in up to 1s seconds connIndex=1
2023-03-16T15:43:07Z INF Unregistered tunnel connection connIndex=1
2023-03-16T15:43:07Z INF Connection 9f30e60d-ef85-4b57-a17f-44a371e443a5 registered connIndex=1 location=LHR
2023-03-16T15:44:26Z INF Lost connection with the edge connIndex=1
2023-03-16T15:44:26Z ERR Serve tunnel error error="connection with edge closed" connIndex=1
2023-03-16T15:44:26Z INF Retrying connection in up to 1s seconds connIndex=1
2023-03-16T15:44:26Z INF Unregistered tunnel connection connIndex=1
2023-03-16T15:44:26Z INF Lost connection with the edge connIndex=0
2023-03-16T15:44:26Z ERR Serve tunnel error error="connection with edge closed" connIndex=0
2023-03-16T15:44:26Z INF Retrying connection in up to 1s seconds connIndex=0
2023-03-16T15:44:26Z INF Unregistered tunnel connection connIndex=0
2023-03-16T15:44:27Z INF Connection cd3e7c11-d9d4-48a2-9ae7-62e030f16414 registered connIndex=0 location=MAN
2023-03-16T15:44:28Z INF Connection 0659fcdc-f962-416f-b219-a9a0fe4a0501 registered connIndex=1 location=LHR
2023-03-16T15:44:35Z INF Lost connection with the edge connIndex=0
2023-03-16T15:44:35Z ERR Serve tunnel error error="connection with edge closed" connIndex=0
2023-03-16T15:44:35Z INF Unregistered tunnel connection connIndex=0
2023-03-16T15:44:35Z INF Retrying connection in up to 1s seconds connIndex=0
2023-03-16T15:44:37Z INF Connection d95c356e-c03f-4a7b-a821-0306ba8d8cd9 registered connIndex=0 location=MAN
2023-03-16T15:45:06Z INF Lost connection with the edge connIndex=2
2023-03-16T15:45:06Z ERR Serve tunnel error error="connection with edge closed" connIndex=2
2023-03-16T15:45:06Z INF Retrying connection in up to 1s seconds connIndex=2
2023-03-16T15:45:06Z INF Unregistered tunnel connection connIndex=2
2023-03-16T15:45:08Z INF Connection e987ac3a-a92a-4e5b-81cc-65ac23dac43a registered connIndex=2 location=MAN
2023-03-16T15:45:15Z INF Lost connection with the edge connIndex=1
2023-03-16T15:45:15Z ERR Serve tunnel error error="connection with edge closed" connIndex=1
2023-03-16T15:45:15Z INF Unregistered tunnel connection connIndex=1
2023-03-16T15:45:15Z INF Retrying connection in up to 1s seconds connIndex=1
2023-03-16T15:45:15Z INF Connection 7f250869-5660-4171-8479-f864e0c09a33 registered connIndex=1 location=LHR
```

**Comment by sudarshan-reddy** [comment]
Hey guys... So sorry that you are having these problems. I am looking at this right now and trying to get to the bottom of this. 

For quick remediation, I notice that 2/3 reports use http2 protocol (I'm not sure what @crackalak is connecting with). Can I recommend you change protocol to `quic` and see if this alleviates your problems for now? 

If you could also share your tunnel IDs,  it helps us look it up faster (I have @pirate 's and I do see your tunnel disconnecting from our servers in the last 30-45 mins. At the moment I cannot see anything on our side causing this but I'm still investigating). 

Also, having a timeline would help me zone in better on what is causing this. @pirate , am I right that you are only seeing this problem since yesterday or have you had this before? 

Others, feel free to chime in as well.

**Comment by pirate** [comment]
QUIC has never worked for us since it was introduced, it never even connects (we've always been using HTTP2 for this reason). Possibly because the upstream service doesn't support QUIC, or maybe a middlebox is blocking it?

The first disconnection was March 9th across all tunnels, then it worked March 9th - March 15th. March 15th EST nighttime it dropped and has continued dropping repeatedly through today.

Thanks for the rapid help.

**Comment by crackalak** [comment]
@sudarshan-reddy I was also connecting with http2. I have now updated my 2 affected tunnels to 2023.3.1 and connected using quic. All is working well and no errors logged in the last 15 minutes that it has been running.

**Comment by terabitti** [comment]
@sudarshan-reddy Thank you for looking this issue. I actually see these problems already at 2023-02-22 (about 1 drop per) hour but it has increased since. Now it’s about 1 drop per minute. I have never managed to connect with quic: "failed to dial to edge with quic: timeout: no recent network activity"

Tunnel ID: 0ad3c7c4-71f7-4384-b788-50ea5100c2b0

**Comment by sudarshan-reddy** [comment]
Hey friends... I looked for anomalies in our servers to see if we were dropping these connections and it does not seem so. I'm also noting that Tunnels are designed to be connected to different locations just to make sure we guard against network partitions. 

1. We haven't made any releases in the past week that would suddenly cause our systems to behave this way. 
2. @pirate also kindly tested this on an older version of cloudflared to confirm they were still having the issue. 

Can we also try to see if there is something the matter with the network on your side that may cause this. I only ask because we have 1000s of tunnels connected right now not seeing these disconnects (this is something I just verified thanks to these reports) . 

I am especially concerned with @terabitti seeing these reconnects in increasing frequency. 

Where are y'all running your Tunnels (I see @pirate runs it on Digital Ocean. Are those the only tunnels that are having trouble connecting right now?).

**Comment by pirate** [comment]
We are also seeing connections dropping increasingly from a few Vultr servers.

**Comment by crackalak** [comment]
@sudarshan-reddy you can see from my logs that we were having disconnections from both MAN and LHR locations. We are hosting on Azure Kubernetes Service.

**Comment by terabitti** [comment]
I'm using UpCloud. I have fully restarted my VM’s, still the same problem. There’s actually another tunnel (731acbcf-4a8d-41a0-8f1f-7b326c6e2015) having connection drops but not so frequently. I also have three other servers/tunnels without these problems (one of them is very similar as the other 2 problematic).

**Comment by terabitti** [comment]
I have done some gateway changes to my server(s) and it allowed me to connect using QUIC. It certainly looks like this helped with the connection issues.

**Comment by pirate** [comment]
Unfortunately QUIC doesn't work for our server, still seeing the disconnections every few hours here

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/511499/225801320-989fb7b9-ac1f-4a7e-a35e-13a7800a2a89.png">

**Comment by terabitti** [comment]
Before switching to QUIC I was getting ”Lost connection with the edge” about every 2 minutes. After switching to QUIC I have seen ”timeout: no recent network activity” only a few times in 6-7 hours. That’s a huge change and am not worried about those infrequent errors.

I still have one http2 tunnel (not migrated to QUIC yet) throwing ”Lost connection with the edge” about 10 times per hour (increased from yesterday).

It wasn’t very straightforward to get QUIC working on our end (had to change networks/gateways), but fortunately it was possible. I have to migrate other servers to this too.

**Comment by sudarshan-reddy** [comment]
> I have a question though: in theory tunnels are resilient to intermittent connections though right? Even if we did have packet loss (which I think is unlikely across multiple providers), wouldn't it reconnect automatically?


Indeed, this is the expectation. I see some re-registers in your initial logs:

```
argo_1      | 2023-03-16T05:14:44Z INF Connection 17872c64-60d8-43dc-bdfd-8e2b54a1034a registered with protocol: http2 connIndex=0 ip=198.41.192.67 location=EWR
```

Do you not see this behaviour anymore? Or are you saying this registered connection doesn't help? 

If it's the latter, I'm inclined to investigate in the direction of something on the client side stopping this traffic. 

I noticed you mentioned you are seeing this on your VULTR services. Do you see it on other deployments also or is it isolated to here?

**Comment by sudarshan-reddy** [comment]
Thanks @terabitti . That really helps me zone in on the blast radius.

**Comment by sudarshan-reddy** [comment]
Also @terabitti did 

```
After switching to QUIC I have seen ”timeout: no recent network activity” only a few times in 6-7 hours.
```

cause downtime or was it just one of our redundant connections?

**Comment by terabitti** [comment]
@sudarshan-reddy No downtime. These connection timeouts happens occasionally with QUIC but no complete downtime. At least not as long as our monitoring system could catch.

**Comment by morpig** [comment]
@pirate can you try running cloudflared in host level and not docker? just to check whether it's a docker issue or not.

talking about tunnels, I have no issue running http/2 in do, linode, vultr, even dedicated server providers. 

esp cloud providers having peering/PNI with cloudflare, connections should be fine.

<img width="495" alt="Screenshot 2023-03-18 at 17 46 11" src="https://user-images.githubusercontent.com/4915643/226100766-3cedec22-bdf6-4181-9c71-fc6302ff4bc9.png">

**Comment by jonseymour** [comment]
We are also experiencing this with docker based tunnels running http2. We are on 2023.3.1. It started occurring on 17 March when were were on 2023.1.0

**Comment by pirate** [comment]
> 1. Creating and connecting a tunnel that doesn't see any traffic on the same machine where you see tunnel disconnects. Do both tunnels restart or is it only tunnels that see traffic?

Haven't been able to reproduce it like this with a fresh tunnel. It's only a few specific tunnels that receive traffic that have have the disconnecting issue.

> 2. Also, what are your traffic patterns like? Did you see a sudden increase in traffic around this time?

We have not seen any sudden increase in traffic as far as I can tell. We are also getting disconnects on some fairly low-traffic tunnels.

> @pirate can you try running cloudflared in host level and not docker? just to check whether it's a docker issue or not.

Unfortunately docker is critical for us, our entire deployment/ops system relies on everything being run in docker. I tried just to test and wasn't able to reproduce it, but practically speaking we can't run our deployments in prod without docker so it would be a dealbreaker for us to remove it.

**Comment by jonseymour** [comment]
FWIW: i am seeing this running cloudflared in AWS ECS Fargate containers in ap-southeast-2.

**Comment by realies** [comment]
QUIC is much more stable for me than HTTP2; the tunnels go down every few days. But HTTP2 is much faster in terms of latency and bandwidth (between 5-10x), despite failing almost daily. This is what an HTTP2 tunnels failure looks like:
```
2023-03-20T13:29:17Z WRN Connection terminated error="DialContext error: dial tcp 198.41.200.13:7844: i/o timeout" connIndex=2
2023-03-20T13:29:34Z WRN Connection terminated error="DialContext error: dial tcp 198.41.192.227:7844: i/o timeout" connIndex=0
2023-03-20T13:29:40Z WRN Connection terminated error="DialContext error: dial tcp 198.41.192.167:7844: i/o timeout" connIndex=3
2023-03-20T13:29:59Z INF Lost connection with the edge connIndex=1
2023-03-20T13:29:59Z INF Unregistered tunnel connection connIndex=1
2023-03-20T13:29:59Z WRN Serve tunnel error error="connection with edge closed" connIndex=1 ip=198.41.200.43
2023-03-20T13:29:59Z INF Retrying connection in up to 1s connIndex=1 ip=198.41.200.43
2023-03-20T13:30:00Z ERR Connection terminated error="connection with edge closed" connIndex=1
```

**Comment by morpig** [comment]
> 2023-03-20T13:29:17Z WRN Connection terminated error="DialContext error: dial tcp 198.41.200.13:7844: i/o timeout" connIndex=2
2023-03-20T13:29:34Z WRN Connection terminated error="DialContext error: dial tcp 198.41.192.227:7844: i/o timeout" connIndex=0

is that running under docker? it's timing out to 2 different regions, that's weird...

**Comment by realies** [comment]
@morpig, a Docker container, yes. There's a QUIC container running side by side with the HTTP2 one serving another tunnel and it has not had any issues.

**Comment by pirate** [comment]
Mine was also timing out to multiple regions, I just only copied enough log output previously to show one failure at a time, sry. I can post more failing lines if it's helpful.

**Comment by jonseymour** [comment]
I have also found relief by upgrading to QUIC. 

One tip for doing this in AWS infrastructure is that the AWS NAT gateways appear to rewrite the source address of inbound QUIC packets so that they appear to come from the NAT Gateway rather than the cloudflare edge servers. As a result, I had to add additional ACL rules to cope with this unexpected occurrence. I have no idea why the NAT Gateways do this but it seems they do.

**Comment by duyhenryer** [comment]
Hi
I have 2 tunnels running with version `2023.2.2`
Default protocol: `auto`
So 2 days ago, I had to change the protocol to `quic` for a tunnel.
Within 2 days I monitoring then I look unstable connections to the tunnels
This is monitoring for the tunnel  to changed the protocol to `quic`

![Screenshot 2023-03-23 at 10 29 27](https://user-images.githubusercontent.com/21151778/227094787-46b2a4c2-dbab-4dc6-9171-36d1403cdf23.png)

This is monitoring for the tunnel with the protocol to `auto`
<img width="1336" alt="Screenshot 2023-03-23 at 10 29 59" src="https://user-images.githubusercontent.com/21151778/227094867-32af5bf5-5d87-4d3e-95ca-93a34e675e0f.png">

Any update this problem?
Thanks all

**Comment by joliveirinha** [comment]
Additionally @pirate , if you are able to reproduce this in low traffic tunnels, could you enable debug logging in cloudflared as well as http2 debugging to help us identify what is causing your connection to fail?

We already validated in our side that these connections go into a bad state and that is why they are closed.

So, if you could setup a tunnel where you can reproduce  this and gives us the logs, that would be ideal:

The command to run would be something like this: 
GODEBUG=http2debug=2 cloudflared tunnel --loglevel debug --ha-connections 1 --protocol http2 --url localhost:8090

Again, ideally you would do this in a low traffic tunnel. 
Thanks.

**Comment by pirate** [comment]
@joliveirinha I will add those parameters and post back with the debug logs, in the meantime here is the tunnel ID of our failing tunnel: `36b92ebc-34ff-40f1-8bb5-48d9eaf4dbd9`

```logs
argo_1      | 2023-03-23T19:29:59Z INF Reusing existing tunnel with this name tunnelID=36b92ebc-34ff-40f1-8bb5-48d9eaf4dbd9
argo_1      | 2023-03-23T19:29:59Z INF docs.zervice.io is already configured to route to your tunnel
argo_1      | 2023-03-23T19:29:59Z INF Starting tunnel tunnelID=36b92ebc-34ff-40f1-8bb5-48d9eaf4dbd9
argo_1      | 2023-03-23T19:29:59Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
argo_1      | 2023-03-23T19:29:59Z INF Version 2022.12.1
argo_1      | 2023-03-23T19:29:59Z INF GOOS: linux, GOVersion: go1.19.4, GoArch: amd64
argo_1      | 2023-03-23T19:29:59Z INF Settings: map[f:true hostname:docs.zervice.io n:hedgedoc.zervice.io name:hedgedoc.zervice.io no-autoupdate:true overwrite-dns:true p:http2 protocol:http2 retries:15 url:http://hedgedoc:3000]
argo_1      | 2023-03-23T19:29:59Z INF Generated Connector ID: 1e52cd36-0798-405c-acf0-52536eafc444
argo_1      | 2023-03-23T19:29:59Z INF Initial protocol http2
argo_1      | 2023-03-23T19:29:59Z INF ICMP proxy will use 172.21.0.2 as source for IPv4
argo_1      | 2023-03-23T19:29:59Z INF ICMP proxy will use :: as source for IPv6
argo_1      | 2023-03-23T19:29:59Z INF Starting metrics server on 127.0.0.1:33971/metrics
argo_1      | 2023-03-23T19:29:59Z WRN Your version 2022.12.1 is outdated. We recommend upgrading it to 2023.3.1
argo_1      | 2023-03-23T19:29:59Z INF Connection ec00f7f8-ab25-4a31-9ff2-bcbd3265d446 registered with protocol: http2 connIndex=0 ip=198.41.192.227 location=EWR
argo_1      | 2023-03-23T19:30:00Z INF Connection ee48d06a-3521-4b66-aa1c-6b1714457775 registered with protocol: http2 connIndex=1 ip=198.41.200.33 location=ORD
argo_1      | 2023-03-23T19:30:01Z INF Connection 4e10b9b0-4823-499a-aa1d-61645879255d registered with protocol: http2 connIndex=2 ip=198.41.200.13 location=ORD
argo_1      | 2023-03-23T19:30:02Z INF Connection 3753161c-cf6b-41f1-af7d-107ac5091161 registered with protocol: http2 connIndex=3 ip=198.41.192.37 location=EWR
argo_1      | 2023-03-23T19:31:19Z INF Lost connection with the edge connIndex=2
argo_1      | 2023-03-23T19:31:19Z WRN Serve tunnel error error="connection with edge closed" connIndex=2 ip=198.41.200.13
argo_1      | 2023-03-23T19:31:19Z INF Unregistered tunnel connection connIndex=2
argo_1      | 2023-03-23T19:31:19Z INF Retrying connection in up to 1s connIndex=2 ip=198.41.200.13
argo_1      | 2023-03-23T19:31:21Z WRN Connection terminated error="connection with edge closed" connIndex=2
argo_1      | 2023-03-23T19:31:25Z INF Connection 10fecc58-fedc-430f-aab2-47841d2b5674 registered with protocol: http2 connIndex=2 ip=198.41.200.13 location=ORD
```

**Comment by pirate** [comment]
We're now seeing it go down multiple times per hour, any ideas on temporary fixes other than QUIC @joliveirinha? Can I up the number of HA connections to 10+ maybe so it takes longer before they all fail?

```logs
argo_1      | 2023-03-28T17:24:57Z INF Unregistered tunnel connection connIndex=0
argo_1      | 2023-03-28T17:24:57Z INF Lost connection with the edge connIndex=0
argo_1      | 2023-03-28T17:24:57Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=7af191b32bd27148-YUL originService=http://hedgedoc:3000
argo_1      | 2023-03-28T17:24:57Z ERR failed to serve incoming request error="Failed to proxy HTTP: Incoming request ended abruptly: context canceled"
argo_1      | 2023-03-28T17:24:57Z WRN Serve tunnel error error="connection with edge closed" connIndex=0 ip=198.41.200.23
argo_1      | 2023-03-28T17:24:57Z INF Retrying connection in up to 1s connIndex=0 ip=198.41.200.23
argo_1      | 2023-03-28T17:24:58Z WRN Connection terminated error="connection with edge closed" connIndex=0
...
argo_1      | 2023-03-28T17:26:17Z INF Lost connection with the edge connIndex=2
argo_1      | 2023-03-28T17:26:17Z WRN Serve tunnel error error="connection with edge closed" connIndex=2 ip=198.41.200.33
argo_1      | 2023-03-28T17:26:17Z INF Retrying connection in up to 1s connIndex=2 ip=198.41.200.33
argo_1      | 2023-03-28T17:26:17Z INF Unregistered tunnel connection connIndex=2
argo_1      | 2023-03-28T17:26:17Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=7af1939dba7d4308-EWR originService=http://hedgedoc:3000
argo_1      | 2023-03-28T17:26:17Z ERR failed to serve incoming request error="Failed to proxy HTTP: Incoming request ended abruptly: context canceled"
argo_1      | 2023-03-28T17:26:17Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=7af193a139bf7148-YUL originService=http://hedgedoc:3000
argo_1      | 2023-03-28T17:26:17Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=7af193abeae07148-YUL originService=http://hedgedoc:3000
argo_1      | 2023-03-28T17:26:17Z ERR failed to serve incoming request error="Failed to proxy HTTP: Incoming request ended abruptly: context canceled"
argo_1      | 2023-03-28T17:26:17Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=7af1939dca884308-EWR originService=http://hedgedoc:3000
argo_1      | 2023-03-28T17:26:17Z ERR failed to serve incoming request error="Failed to proxy HTTP: Incoming request ended abruptly: context canceled"
argo_1      | 2023-03-28T17:26:17Z ERR failed to serve incoming request error="Failed to proxy HTTP: Incoming request ended abruptly: context canceled"
argo_1      | 2023-03-28T17:26:19Z WRN Connection terminated error="connection with edge closed" connIndex=2
argo_1      | 2023-03-28T17:26:37Z INF Lost connection with the edge connIndex=3
argo_1      | 2023-03-28T17:26:37Z INF Unregistered tunnel connection connIndex=3
argo_1      | 2023-03-28T17:26:37Z ERR Serve tunnel error error="connection with edge closed" connIndex=3 ip=198.41.192.7
argo_1      | 2023-03-28T17:26:37Z INF Retrying connection in up to 1s connIndex=3 ip=198.41.192.7
argo_1      | 2023-03-28T17:26:38Z ERR Connection terminated error="connection with edge closed" connIndex=3
```

**Comment by joliveirinha** [comment]
Hi @pirate. Thanks for the logs. I spent some time reviewing the logs last Friday, but I couldn't find a particular reason for the disconnects.

We can indeed validate that the only Goaway frame processed is from our edge to cloudflared and it is sent without an "error". This is the close of the connection we trigger because we detected that the connection was not able to process any requests anymore.

Looking deep into the golang http2 code, we have a possible root cause that could be triggering this.
However, we will only be able to start a edge release next week and validate if this fixes the problem.

Once validate this we will write here about next steps.

Again, thanks for the logs. It was helpful to focus in one direction.

**Comment by joliveirinha** [comment]
Hi @pirate .

Sorry for the delay, but we had other priorities and we were not able to release the change before.
The release of the change we made to try and mitigate this was done today and we see a decrease of disconnects when using http2.

can you validate from your side if it improved?

Thanks.

**Comment by obezuk** [comment]
This issue has grown quite large, and appears to have been addressed by @joliveirinha's last update. To keep us focused on on-going needs of the community I'm going to close this. If anyone is still experiencing issues, please file a new ticket with the latest version of cloudflared and fresh logs.

**Comment by ycjcl868** [comment]
We are also experiencing this with docker based tunnels running http2. We are on 2023.5.0. logs:

```bash
Tue May  9 07:33:05 2023 daemon.err cloudflared[4748]: 2023-05-08T23:33:05Z INF Registered tunnel connection connIndex=0 connection=8ae8cc37-84a8-45df-a8d2-51efbd0968ba event=0 ip=198.41.192.67 location=NRT protocol=http2
Tue May  9 07:33:06 2023 daemon.err cloudflared[4748]: 2023-05-08T23:33:06Z INF Registered tunnel connection connIndex=1 connection=da4a2156-d898-4301-b5d1-43be0ac8015d event=0 ip=198.41.200.113 location=KIX protocol=http2
Tue May  9 07:33:07 2023 daemon.err cloudflared[4748]: 2023-05-08T23:33:07Z INF Registered tunnel connection connIndex=2 connection=f481dfc2-3433-4505-8751-477d5ef5deea event=0 ip=198.41.192.77 location=NRT protocol=http2
Tue May  9 07:33:09 2023 daemon.err cloudflared[4748]: 2023-05-08T23:33:09Z INF Registered tunnel connection connIndex=3 connection=7c9dbec3-7479-471e-ae12-173944f37835 event=0 ip=198.41.200.63 location=KIX protocol=http2
Tue May  9 08:29:23 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:23Z INF Lost connection with the edge connIndex=1
Tue May  9 08:29:23 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:23Z INF Unregistered tunnel connection connIndex=1 event=0 ip=198.41.200.113
Tue May  9 08:29:23 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:23Z WRN Serve tunnel error error="connection with edge closed" connIndex=1 event=0 ip=198.41.200.113
Tue May  9 08:29:23 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:23Z INF Retrying connection in up to 1s connIndex=1 event=0 ip=198.41.200.113
Tue May  9 08:29:23 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:23Z WRN Connection terminated error="connection with edge closed" connIndex=1
Tue May  9 08:29:29 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:29Z INF Lost connection with the edge connIndex=0
Tue May  9 08:29:29 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:29Z INF Unregistered tunnel connection connIndex=0 event=0 ip=198.41.192.67
Tue May  9 08:29:29 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:29Z WRN Serve tunnel error error="connection with edge closed" connIndex=0 event=0 ip=198.41.192.67
Tue May  9 08:29:29 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:29Z INF Retrying connection in up to 1s connIndex=0 event=0 ip=198.41.192.67
Tue May  9 08:29:31 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:31Z WRN Connection terminated error="connection with edge closed" connIndex=0
Tue May  9 08:29:32 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:32Z INF Lost connection with the edge connIndex=2
Tue May  9 08:29:32 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:32Z INF Unregistered tunnel connection connIndex=2 event=0 ip=198.41.192.77
Tue May  9 08:29:32 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:32Z WRN Serve tunnel error error="connection with edge closed" connIndex=2 event=0 ip=198.41.192.77
Tue May  9 08:29:32 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:32Z INF Retrying connection in up to 1s connIndex=2 event=0 ip=198.41.192.77
Tue May  9 08:29:34 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:34Z WRN Connection terminated error="connection with edge closed" connIndex=2
Tue May  9 08:29:38 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:38Z WRN Unable to establish connection with Cloudflare edge error="TLS handshake with edge error: EOF" connIndex=1 event=0 ip=198.41.200.113
Tue May  9 08:29:38 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:38Z WRN Serve tunnel error error="TLS handshake with edge error: EOF" connIndex=1 event=0 ip=198.41.200.113
Tue May  9 08:29:38 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:38Z INF Retrying connection in up to 4s connIndex=1 event=0 ip=198.41.200.113
Tue May  9 08:29:38 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:38Z WRN Unable to establish connection with Cloudflare edge error="TLS handshake with edge error: EOF" connIndex=0 event=0 ip=198.41.192.67
Tue May  9 08:29:38 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:38Z WRN Serve tunnel error error="TLS handshake with edge error: EOF" connIndex=0 event=0 ip=198.41.192.67
Tue May  9 08:29:38 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:38Z INF Retrying connection in up to 4s connIndex=0 event=0 ip=198.41.192.67
Tue May  9 08:29:39 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:39Z WRN Unable to establish connection with Cloudflare edge error="TLS handshake with edge error: EOF" connIndex=2 event=0 ip=198.41.192.77
Tue May  9 08:29:39 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:39Z WRN Serve tunnel error error="TLS handshake with edge error: EOF" connIndex=2 event=0 ip=198.41.192.77
Tue May  9 08:29:39 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:39Z INF Retrying connection in up to 4s connIndex=2 event=0 ip=198.41.192.77
Tue May  9 08:29:41 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:41Z WRN Connection terminated error="TLS handshake with edge error: EOF" connIndex=0
Tue May  9 08:29:42 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:42Z WRN Connection terminated error="TLS handshake with edge error: EOF" connIndex=1
Tue May  9 08:29:43 2023 daemon.err cloudflared[4748]: 2023-05-09T00:29:43Z WRN Connection terminated error="TLS handshake with edge error: EOF" connIndex=2
Tue May  9 08:30:15 2023 daemon.err cloudflared[4748]: 2023-05-09T00:30:15Z WRN Unable to establish connection with Cloudflare edge error="TLS handshake with edge error: EOF" connIndex=1 event=0 ip=198.41.200.13
Tue May  9 08:30:15 2023 daemon.err cloudflared[4748]: 2023-05-09T00:30:15Z WRN Serve tunnel error error="TLS handshake with edge error: EOF" connIndex=1 event=0 ip=198.41.200.13
Tue May  9 08:30:15 2023 daemon.err cloudflared[4748]: 2023-05-09T00:30:15Z INF Retrying connection in up to 8s connIndex=1 event=0 ip=198.41.200.13
```

**Comment by sudarshan-reddy** [comment]
@ycjcl868 : Are you still seeing this? We rolled out an edge release that could have potentially fixed your problem.

**Comment by pirate** [comment]
Unrelated to @ycjcl868's issue, I just checked most of our servers and I believe the original issue is fixed for us. Thanks

**Comment by ycjcl868** [comment]
> @ycjcl868 : Are you still seeing this? We rolled out an edge release that could have potentially fixed your problem.

yes

**Comment by Kaijun** [comment]
@sudarshan-reddy @pirate i'm still encountering this issue with version  2023.6.1

`cloudflared` keeps connecting but always get error `Unable to establish connection with Cloudflare edge error`

but if i restart cloudflared, it starts working fine without any connection problem.

Is this problem fixed with version  2023.6.1?

And by the way, is it possible to **make cloudflared exit if error occured** and max reties exceeded? so that the systemd/docker can restart the program to solve the problem

**Comment by Kaijun** [comment]
And in my case, the connection seems to be closed by server unexpectedly.
```
TLS handshake with edge error: read tcp 192.168.123.3:62830->198.18.1.69:7844: read: connection reset by peer
```

**Comment by masterwishx** [comment]
is some one got fixed this issue?

**Comment by amalcev** [comment]
Still not fixed

**Comment by amalcev** [comment]
> Additionally, I would like to inquire whether **it is possible to configure cloudflared to automatically exit when an error occurs** and the maximum number of retries has been reached. This would allow systemd or Docker to restart the program and resolve the problem.

Is there a way to do this?

**Comment by jjh42** [comment]
We have been running a cloudflare tunnel with http2 fine for months, but in the last approximately 1 week we have started seeing this issue (frequent disconnections from edge).

We have tried upgrading to the latest cloudflared (2025.1) but that did not help. I have opened a ticket.

**Comment by KaliforniaGator** [comment]
It is Apr 1 2025, and no joke, this is still a big problem. I have to restart my tunnels on a daily basis or my websites fail to connect to edge and go down for the entire day. You have to prioritize fixing essential services, your customers will leave and not pay you another dime because you guys "Don't have time" to fix these critical issues. I'm sure most of the people who commented eventually just went with another option cause this is exhausting. I'm already looking at other reverse proxy options, but please fix at least try to fix it.

**Comment by pirate** [comment]
It is almost certainly a different issue @KaliforniaGator, you should open a new issue as this one is already closed and wont get noticed.

**Comment by KaliforniaGator** [comment]
@pirate its not a different issue bro. 

`ERR Connection terminated error="connection with edge closed" connIndex=2
2025-04-03 20:18:13 2025-04-04T00:18:13Z ERR Connection terminated error="connection with edge closed" connIndex=0
2025-04-03 20:18:13 2025-04-04T00:18:13Z ERR Connection terminated error="Error shutting down control stream: client disconnected" connIndex=3
2025-04-03 20:18:14 2025-04-04T00:18:14Z ERR Connection terminated error="connection with edge closed" connIndex=1` 

It's literally exactly the same, the title of this thread is what brought me here, I typed my exact problem on google and BAM! HERE IT IS! so yeah, it is the same. Maybe that's the problem, developers for this program don't wanna have to do any work so they attribute it to fantasy reasons instead of fixing the actual issue. Hell at this point I might as well look at the source code and fix it myself.

**Comment by KaliforniaGator** [comment]
[New Issue Opened](https://github.com/cloudflare/cloudflared/issues/1440)

**Comment by dr3x** [comment]
Still happening in 2026 — cross-linking from a more detailed report I just
posted on #1440 with logs from today (2026-07-13, cloudflared 2026.6.0):
https://github.com/cloudflare/cloudflared/issues/1440#issuecomment-4960655532

Same shape as described here: all HA connections lost within a 1-2s window,
reconnecting together shortly after, repeating continuously (every 2-4 min
in our case, 398 events/6h). Notable overlap with this issue specifically:
we switched from QUIC to `--protocol http2` assuming a local UDP/NAT issue,
and saw the *exact same lockstep pattern continue unchanged* on HTTP/2 — so
whatever's causing this doesn't look protocol-specific, which matches your
report of it hitting multiple cloud providers with no home NAT involved at
all. Still open 3+ years later; would be good to get engineering eyes on
whether this is edge-side connection rotation vs. a client bug.
